### ISSUE TITLE
Deprecation warning in pem module (node v7.0.0)

### ISSUE THREAD

**Issue by ilyash** [beameio/beame-sdk#20]
`node --trace-deprecation beame-insta-ssl create ...`
Produces
```
(node:17427) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at makeCallback (fs.js:103:12)
    at Object.fs.unlink (fs.js:979:14)
    at /usr/local/n/versions/node/4.4.0/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/node_modules/pem/lib/pem.js:1028:16
    at Array.forEach (native)
    at /usr/local/n/versions/node/4.4.0/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/node_modules/pem/lib/pem.js:1027:15
    at /usr/local/n/versions/node/4.4.0/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/node_modules/pem/lib/pem.js:939:13
    at testOpenSSLPath (/usr/local/n/versions/node/4.4.0/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/node_modules/pem/lib/pem.js:1100:9)
    at spawnOpenSSL (/usr/local/n/versions/node/4.4.0/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/node_modules/pem/lib/pem.js:919:5)
    at spawnWrapper (/usr/local/n/versions/node/4.4.0/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/node_modules/pem/lib/pem.js:1026:5)
    at execOpenSSL (/usr/local/n/versions/node/4.4.0/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/node_modules/pem/lib/pem.js:1043:5)
```

**Comment by ilyash** [comment]
Opened upstream issue: https://github.com/Dexus/pem/issues/103
